export default class Constants {
  static AUDIO_TYPE_NONE = "0"
  static AUDIO_TYPE_NONE_NAME = "None"
  static AUDIO_TYPE_RECEIVER = "1"
  static AUDIO_TYPE_RECEIVER_NAME = "Receiver"
  static AUDIO_TYPE_SPEAKER = "2"
  static AUDIO_TYPE_SPEAKER_NAME = "Speaker"
  static AUDIO_TYPE_HEADSET = "3"
  static AUDIO_TYPE_HEADSET_NAME = "Headset"
  static AUDIO_TYPE_BLUETOOTH = "4"
  static AUDIO_TYPE_BLUETOOTH_NAME = "Bluetooth"
}